name = "sqlite3"
description = "SQLite is a C library that implements an SQL database engine."
version = "3.42.0"

authors = ["D. Richard Hipp <drh@hwaci.com>"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "blessing"
website = "https://www.sqlite.org/"
tags = []
